### ISSUE TITLE
Compute optimal fanout and min

### ISSUE THREAD

**Issue by jhryniw** [rubynetix/consort#6]
Compute the maximum number of threads we want to create based on the size of the data or some user specified values passed to the sort function. From this, calculate a good **fanout** and **min** sorting size for the problem.

This would avoid the problem that we can only create so many threads (~2000) and probably much less than that efficiently (~100).

**Comment by fbulbuc** [comment]
I attempted to replace the need for this using thread pools, as you suggested, but it resulted in a slower sort. Instead, I have added a calculation for the number of threads needed given the fanout and single-thread-threshold -- see #17.
